development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: monologue_dev
  pool: 5
  username: monologue
  password:

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: monologue_test
  pool: 5
  username: monologue
  password:
